name: Publish Static Site
run-name: Publish REF({{ github.ref }})

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25.2.1
      - name: Build Static Site Content (React)
        run: |
          npm run build
          
      - name: Create and Upload Archive
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish Archive to GitHub Pages
        id: publish
        uses: actions/deploy-pages@4
