name: Build and Publish Site
description: Build Static Site Content (React)
run-name: Build REF({{ github.head_ref }})

on:
  push:
    branches:
      - none

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25.2.1
      - name: Build Site
        run: |
          npm run build
      - name: Create and Upload Archive
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out

  build_bun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11
      - name: Build Site
        run: |
          bun run build
      - name: Create and Upload Archive
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out

  build_deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Deno
        run: |
          echo Setup Deno
      - name: Build Site
        run: |
          deno run build
      - name: Create and Upload Archive
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out
  

  deploy_node:
    needs: build_node
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.build_node.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish Archive to GitHub Pages
        id: publish
        uses: actions/deploy-pages@4