name: Verify Pull Request
description: 
run-name: Verify REFF({{ inputs.ref }})

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubunut-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25.2.1
          cache: npm
          
      - name: Install Node Dependencies
        run: |
          npm ci

      - name: Run Tests
        id: tests
        run: |
          npm run test

      - name: Enforce Formatting
        id: lint
        run: |
          npm run lint
